In [1]:
from bddmodel import BDDModel
import tensorflow as tf
from bddfunc import training_batcher
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [2]:
my_model = BDDModel()

Instructions for updating:
Use keras.layers.conv2d instead.
Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use keras.layers.max_pooling2d instead.


In [3]:
batcher = training_batcher(0, 16)
enc = OneHotEncoder(sparse=False, categories=[np.arange(10)])

In [ ]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    init.run()
    for data, labels in batcher:
        temp = enc.fit_transform(np.reshape(labels, (-1,1)))
        print(temp.shape)
        f_dict = {my_model.X: data, my_model.Y1: temp}
        my_model.minimizer.run(feed_dict=f_dict)
        print(my_model.loss.eval(feed_dict=f_dict))

(16, 10)
682.443
(16, 10)
136690.7
(16, 10)
3156891.0
(16, 10)
794948.0
(16, 10)
672540.5
(16, 10)
75475.06
(16, 10)
6065270.5
(16, 10)
2406741.0
(16, 10)
361886.8
(16, 10)
1541866.5
(16, 10)
194119.1
(16, 10)
157012.53
(16, 10)
371122.3
(16, 10)
864246.9
(16, 10)
1179417.9
(16, 10)
447398.06
(16, 10)
246400.06
(16, 10)
291408.25
(16, 10)
380102.47
(16, 10)
1264517.0
(16, 10)
562178.9
(16, 10)
52005.85
(16, 10)
228914.72
(16, 10)
221261.55
(16, 10)
149565.84
(16, 10)
113548.7
(16, 10)
139091.02
(16, 10)
130013.42
(16, 10)
157630.25
(16, 10)
194739.62
(16, 10)
75237.9
(16, 10)
653149.44
(16, 10)
180237.75
(16, 10)
362223.25
(16, 10)
218015.22
(16, 10)
236348.61
(16, 10)
235622.47
(16, 10)
157367.31
(16, 10)
52203.094
(16, 10)
83723.34
(16, 10)
40185.438
(16, 10)
30077.652
(16, 10)
24330.924
(16, 10)
50099.67
(16, 10)
41239.066
(16, 10)
60582.29
(16, 10)
61734.156
(16, 10)
50994.117
(16, 10)
127727.42
(16, 10)
70744.59
(16, 10)
81484.69
(16, 10)
141169.11
(16, 10)
65899.41
(16, 10)
31322

In [11]:
import matplotlib.pyplot as plt

In [35]:
import numpy as np
np.max(x[0])

242

In [40]:
x,y = next(yolo)
print(y.shape)

(512,)


In [76]:
enc = OneHotEncoder(sparse=False, categories=[np.arange(10)])

In [77]:
x_shape = np.reshape(y, (-1, 1))

In [81]:
baylyfe =enc.fit_transform(x_shape)

In [85]:
baylyfe[0]

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.])

In [82]:
np.argmax(baylyfe, axis=1)

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 7, 2, 4,
       2, 2, 2, 2, 9, 6, 6, 7, 6, 6, 6, 6, 6, 6, 6, 7, 7, 6, 6, 6, 7, 6,
       7, 4, 4, 4, 2, 2, 7, 7, 6, 6, 6, 6, 6, 4, 4, 2, 2, 2, 7, 7, 2, 2,
       4, 4, 6, 7, 7, 7, 7, 7, 7, 2, 2, 2, 7, 6, 6, 6, 6, 6, 6, 6, 6, 7,
       7, 7, 7, 7, 7, 7, 4, 2, 2, 2, 7, 7, 7, 2, 2, 2, 2, 2, 4, 4, 4, 7,
       7, 6, 2, 2, 7, 6, 6, 7, 2, 2, 7, 6, 6, 7, 7, 7, 7, 7, 6, 6, 6, 7,
       7, 2, 7, 2, 2, 2, 2, 2, 7, 7, 7, 7, 2, 2, 7, 7, 7, 2, 2, 2, 2, 7,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 6, 7, 7, 7, 7, 7, 7, 7, 7, 4, 4,
       4, 2, 2, 2, 2, 6, 6, 6, 2, 2, 2, 7, 7, 7, 7, 7, 7, 7, 7, 2, 2, 2,
       6, 2, 6, 7, 9, 2, 2, 7, 7, 7, 2, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 2, 7, 7, 2, 9, 7, 6, 6, 7, 7, 6, 6, 6, 6, 2, 2, 6, 6, 6, 6,
       6, 7, 7, 7, 7, 7, 2, 2, 2, 4, 2, 6, 6, 2, 2, 2, 7, 7, 7, 7, 7, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 7, 7, 7, 7, 7, 7, 7, 7, 2, 7, 7, 7,
       2, 7, 2, 7, 7, 7, 7, 7, 7, 2, 2, 7, 7, 7, 7,

In [83]:
y

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 7, 2, 4,
       2, 2, 2, 2, 9, 6, 6, 7, 6, 6, 6, 6, 6, 6, 6, 7, 7, 6, 6, 6, 7, 6,
       7, 4, 4, 4, 2, 2, 7, 7, 6, 6, 6, 6, 6, 4, 4, 2, 2, 2, 7, 7, 2, 2,
       4, 4, 6, 7, 7, 7, 7, 7, 7, 2, 2, 2, 7, 6, 6, 6, 6, 6, 6, 6, 6, 7,
       7, 7, 7, 7, 7, 7, 4, 2, 2, 2, 7, 7, 7, 2, 2, 2, 2, 2, 4, 4, 4, 7,
       7, 6, 2, 2, 7, 6, 6, 7, 2, 2, 7, 6, 6, 7, 7, 7, 7, 7, 6, 6, 6, 7,
       7, 2, 7, 2, 2, 2, 2, 2, 7, 7, 7, 7, 2, 2, 7, 7, 7, 2, 2, 2, 2, 7,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 6, 7, 7, 7, 7, 7, 7, 7, 7, 4, 4,
       4, 2, 2, 2, 2, 6, 6, 6, 2, 2, 2, 7, 7, 7, 7, 7, 7, 7, 7, 2, 2, 2,
       6, 2, 6, 7, 9, 2, 2, 7, 7, 7, 2, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 2, 7, 7, 2, 9, 7, 6, 6, 7, 7, 6, 6, 6, 6, 2, 2, 6, 6, 6, 6,
       6, 7, 7, 7, 7, 7, 2, 2, 2, 4, 2, 6, 6, 2, 2, 2, 7, 7, 7, 7, 7, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 7, 7, 7, 7, 7, 7, 7, 7, 2, 7, 7, 7,
       2, 7, 2, 7, 7, 7, 7, 7, 7, 2, 2, 7, 7, 7, 7,

In [51]:
kek = enc.fit(yolo)

ValueError: Expected 2D array, got 1D array instead:
array=[0 1 2 3 4 5 6 7 8 9].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.